#!/bin/sh

# The contents of this file are subject to the terms
# of the Common Development and Distribution License
# (the License). You may not use this file except in
# compliance with the License.
#
# You can obtain a copy of the License at
# https://opensso.dev.java.net/public/CDDLv1.0.html or
# opensso/legal/CDDLv1.0.txt
# See the License for the specific language governing
# permission and limitations under the License.
#
# When distributing Covered Code, include this CDDL
# Header Notice in each file and include the License file
# at opensso/legal/CDDLv1.0.txt.
# If applicable, add the following below the CDDL Header,
# with the fields enclosed by brackets [] replaced by
# your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"
#
# $Id: VerifyArchive,v 1.2 2006-04-27 07:53:27 veiming Exp $
#
# Copyright 2006 Sun Microsystems Inc. All Rights Reserved


APPSERVER=APPSERVERDEPLOYMENT
if [ "$APPSERVER" = "true" ]; then
 DP_HOME=APPSERVERBASEDIR/${PRODUCT_DIR}
 JAVA_HOME=APPSERVERBASEDIR/ias/usr/java
else
 DP_HOME=${BASE_DIR}/${PRODUCT_DIR}
 JAVA_HOME=JDK_PATH
fi
USING_JDK14=IAS7INSTALL

AM_PKG_PREFIX=com.sun.identity.log

if [ -z "${JAVA_HOME}" ] ; then
    if [ -d /usr/java ] ; then
        JAVA_HOME=/usr/java
    else
        echo "JAVA_HOME environment variable not set." 1>&2
        exit 1
    fi
fi

JSS_JAR=TAG_JSS_JAR_PATH/jss4.jar
JSS_SO_PATH=TAG_JSS_SO_PATH
DPADMIN_JAR=${DP_HOME}/lib/am_sdk.jar:${DP_HOME}/lib/am_services.jar
LOCALE_HOME=${DP_HOME}/locale
DP_LIB=${DP_HOME}/lib
DP_CONFIG=IS_INSTALL_ETCDIR/IS_PRODNAME/config
SERVLET_JAR=${DP_HOME}/lib/servlet.jar
LOGGING_JAR=${DP_HOME}/lib/am_logging.jar

DP_CLASSPATH=${LOCALE_HOME}:${DPADMIN_JAR}:${DP_CONFIG}:${DP_LIB}:${JSS_JAR}:${SERVLET_JAR}:${LOGGING_JAR}

if [ -z "$LD_LIBRARY_PATH" ] ; then
  LD_LIBRARY_PATH=${JSS_SO_PATH}
else
  LD_LIBRARY_PATH="${JSS_SO_PATH}:$LD_LIBRARY_PATH"
fi

export LD_LIBRARY_PATH

if [ -z "$CLASSPATH" ]
then
  CLASSPATH="${DP_CLASSPATH}"
else
  CLASSPATH="${DP_CLASSPATH}:$CLASSPATH"
fi

if [ "$USING_JDK14" = "true" ]; then
  BOOTCLASSPATHOPTION=""
else
  BOOTCLASSPATHOPTION="-Xbootclasspath:${JAVA_HOME}/lib/tools.jar:${JAVA_HOME}/jre/lib/rt.jar:${JAVA_HOME}/jre/lib/jce.jar:${JAVA_HOME}/jre/lib/jsse.jar"
fi

# Setup proper LD_LIBRARY_PATH if not already set
${JAVA_HOME}/jre/bin/java -Xms64m -Xmx256m -classpath ${CLASSPATH} -D"amconfig=AMCONFIG" -D"java.protocol.handler.pkgs=com.iplanet.services.comm" -D"com.iplanet.coreservices.configpath=${DP_CONFIG}/ums" -D"max_conn_pool=10" -D"min_conn_pool=1" -D"java.util.logging.config.class=com.sun.identity.log.s1is.LogConfigReader" -D"java.util.logging.manager=com.sun.identity.log.LogManager" ${BOOTCLASSPATHOPTION} ${AM_PKG_PREFIX}.cli.ISArchiveVerify "$@"
