/* The contents of this file are subject to the terms
 * of the Common Development and Distribution License
 * (the License). You may not use this file except in
 * compliance with the License.
 *
 * You can obtain a copy of the License at
 * https://opensso.dev.java.net/public/CDDLv1.0.html or
 * opensso/legal/CDDLv1.0.txt
 * See the License for the specific language governing
 * permission and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL
 * Header Notice in each file and include the License file
 * at opensso/legal/CDDLv1.0.txt.
 * If applicable, add the following below the CDDL Header,
 * with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * $Id: AMEntryEventListener.java,v 1.1 2005-11-01 00:29:27 arvindp Exp $
 *
 * Copyright 2005 Sun Microsystems Inc. All Rights Reserved
 */

package com.iplanet.am.sdk.ldap;

// Java packages
import java.security.AccessController;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;

import netscape.ldap.controls.LDAPPersistSearchControl;
import netscape.ldap.util.DN;

import com.iplanet.am.sdk.AMObjectListener;
import com.iplanet.am.util.Debug;
import com.iplanet.services.ldap.event.DSEvent;
import com.iplanet.services.ldap.event.IDSEventListener;
import com.iplanet.sso.SSOException;
import com.iplanet.sso.SSOToken;
import com.sun.identity.security.AdminTokenAction;
import com.sun.identity.sm.SMSException;
import com.sun.identity.sm.SchemaType;
import com.sun.identity.sm.ServiceSchema;
import com.sun.identity.sm.ServiceSchemaManager;

/**
 * The <code>AMEntryEventListener</code> handles all the events that are
 * triggered by any modification/deletion/renaming LDAP entires which do not
 * contain ACI's. This class implements the <code>com.iplanet.services
 * .ldap.event.IDSEventListener</code>
 * interface.
 */
public class AMEntryEventListener implements IDSEventListener {

    // Filter to separate entires which do not contain aci's
    protected static final String SEARCH_FILTER = "(&(objectclass=*)"
            + "(!(|(objectclass=sunService)(objectclass=sunServiceComponent)"
            + "(aci=*))))";

    protected static final int OPERATIONS = LDAPPersistSearchControl.ADD
            | LDAPPersistSearchControl.MODIFY | LDAPPersistSearchControl.DELETE
            | LDAPPersistSearchControl.MODDN;

    // Instance variables
    private Debug debug = AMEventManager.debug;

    private SSOToken internalToken;

    private Map listeners;

    public AMEntryEventListener() {
        this.listeners = new HashMap();
        try {
            internalToken = (SSOToken) AccessController
                    .doPrivileged(AdminTokenAction.getInstance());
        } catch (Exception le) {
            debug.error("AMEntryEventListener() Exception occurred while "
                    + "getting SSOToken", le);
        }
    }

    private Set getDynamicAttributeNames(String serviceName) {
        Set attrNames = Collections.EMPTY_SET;
        try {
            ServiceSchemaManager sm = new ServiceSchemaManager(serviceName,
                    internalToken);
            ServiceSchema sschema = sm.getSchema(SchemaType.DYNAMIC);
            attrNames = sschema.getAttributeSchemaNames();
        } catch (SMSException smse) {
            if (debug.warningEnabled()) {
                debug.warning("AMEntryEventListener.entryChanged(): "
                        + "caught SMSException: ", smse);
            }
        } catch (SSOException ssoe) {
            if (debug.warningEnabled()) {
                debug.error("AMEntryEventListener.entryChanged(): "
                        + "caught SSOException: ", ssoe);
            }
        }
        return attrNames;
    }

    /**
     * This method will be invoked by the <code>EventService</code> if the
     * events for which this listener registered has been triggered. Since this
     * listener is interested in modifications/deletions/renaming of normal
     * directory entires, it identifies the distinguished names affected by this
     * event and sends a notification to the <code>AMObjectImpl</code> by
     * calling the appropriate method.
     * 
     * @param dsEvent
     *            <code>DSEvent</code> object generated by the
     *            <code>EventService</code>.
     */
    public void entryChanged(DSEvent dsEvent) {
        // Get the "dn" responsible for the event
        DN dn = new DN(dsEvent.getID());
        String normalizedDN = dn.toRFCString().toLowerCase();

        if (debug.messageEnabled()) {
            debug.message("AMEntryEventListener.entryChanged(): DSEvent "
                    + "generated for: " + dn);
        }

        // Check if the event was caused by changes/deletions to cos entries
        // (cosdefinitions & costemplates) and figure out the affected dn
        // subtree. Parse the dn in case of cos related events to find out the
        // affected subtree of dns Examples of costemplate dn:
        // "cn="cn=RoleThree,o=hp.com,o=vortex.com",cn=nsCalUser,
        // o=hp.com,o=vortex.com"
        // affectDNs will be all those which suffix match
        // "o=hp.com,o=vortex.com"
        // Examples of cosdefintion dn:
        // "cn=nsCalUser,o=hp.com,o=vortex.com";
        // affectDNs => "o=hp.com,o=vortex.com"
        boolean cosType = true;
        String affectDNs = "";
        Set attrNames = Collections.EMPTY_SET;
        String serviceName = null;
        String objClasses = dsEvent.getClassName();
        if (objClasses.indexOf("cosClassicDefinition") != -1) {// COS
                                                                // definition
            affectDNs = dn.getParent().toRFCString().toLowerCase();
            // Get the serviceName this applies to, and get the attribute
            // names of this service which impact the DNs.
            serviceName = dn.explodeDN(true)[0];
            attrNames = getDynamicAttributeNames(serviceName);
            if (debug.messageEnabled()) {
                debug.message("AMEntryEventListener.entryChanged() "
                        + "Cos Definition changed for service: " + serviceName
                        + "Dynamic Attributes: " + attrNames);
            }
        } else if (objClasses.indexOf("costemplate") != -1) { // COS template
            affectDNs = dn.getParent().getParent().toRFCString().toLowerCase();
            serviceName = dn.getParent().explodeDN(true)[0];
            attrNames = getDynamicAttributeNames(serviceName);
            if (debug.messageEnabled()) {
                debug.message("AMEntryEventListener." + "entryChanged()"
                        + "Cos template changed for service: " + serviceName
                        + "Dynamic Attributes: " + attrNames);
            }
        } else { // Not cos related - only a single dn affected
            cosType = false;
            affectDNs = dn.toRFCString().toLowerCase();
        }
        if (debug.messageEnabled()) {
            debug.message("AMEntryEventListener.entryChanged(): Affected dn: "
                    + affectDNs + " cosType: " + cosType);
        }

        // Call the listeners
        synchronized (listeners) {
            Set keys = listeners.keySet();
            for (Iterator items = keys.iterator(); items.hasNext();) {
                AMObjectListener listener = (AMObjectListener) items.next();
                Map configMap = (Map) listeners.get(listener);
                if (cosType) {
                    listener.objectsChanged(affectDNs, dsEvent.getEventType(),
                            attrNames, configMap);
                    // first call removes the attributes. now remove the
                    // template.
                    listener.objectChanged(normalizedDN,
                            dsEvent.getEventType(), configMap);
                } else {
                    listener.objectChanged(affectDNs, dsEvent.getEventType(),
                            configMap);
                }
            }
        }
    }

    /**
     * This method is invoked by the <code>EventService</code> if it
     * encounters an error.
     * 
     * @param errorStr
     *            error string.
     */
    public void eventError(String errorStr) {
        debug.error("AMEntryEventListener.eventError(): " + errorStr);
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.iplanet.services.ldap.event.IDSEventListener#allEntriesChanged()
     */
    public void allEntriesChanged() {
        debug.error("AMEntryEventListener: Received all entries changed event"
                + "from event service");
        // Call the listeners
        synchronized (listeners) {
            Set keys = listeners.keySet();
            for (Iterator items = keys.iterator(); items.hasNext();) {
                AMObjectListener listener = (AMObjectListener) items.next();
                listener.allObjectsChanged();
            }
        }
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.iplanet.services.ldap.event.IDSEventListener#getBase()
     */
    public String getBase() {
        return AMEventManager.EVENT_BASE_NODE;
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.iplanet.services.ldap.event.IDSEventListener#getFilter()
     */
    public String getFilter() {
        return SEARCH_FILTER;
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.iplanet.services.ldap.event.IDSEventListener#getOperations()
     */
    public int getOperations() {
        return OPERATIONS;
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.iplanet.services.ldap.event.IDSEventListener#getScope()
     */
    public int getScope() {
        return AMEventManager.EVENT_SCOPE;
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.iplanet.services.ldap.event.IDSEventListener#setListener()
     */
    public void setListeners(Map listener) {
        this.listeners = listener;
    }

}
