package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SsoServerSAML1TrustPrtnrsEntry" MBean.
 */
public interface SsoServerSAML1TrustPrtnrsEntryMBean {

    /**
     * Getter for the "SsoServerSAML1TrustPrtnrName" variable.
     */
    public String getSsoServerSAML1TrustPrtnrName() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML1TrustPrtnrIndex" variable.
     */
    public Integer getSsoServerSAML1TrustPrtnrIndex() throws SnmpStatusException;

}
