package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SsoServerAuthSvc" MBean.
 */
public interface SsoServerAuthSvcMBean {

    /**
     * Access the "SsoServerAuthModulesTable" variable.
     */
    public TableSsoServerAuthModulesTable accessSsoServerAuthModulesTable() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerAuthFailureRate" variable.
     */
    public Long getSsoServerAuthFailureRate() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerAuthSuccessRate" variable.
     */
    public Long getSsoServerAuthSuccessRate() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerAuthFailureCount" variable.
     */
    public Long getSsoServerAuthFailureCount() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerAuthSuccessCount" variable.
     */
    public Long getSsoServerAuthSuccessCount() throws SnmpStatusException;

}
