package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SsoServerPolicyWebGroupEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.2.1.
 */
public class SsoServerPolicyWebGroupEntry implements SsoServerPolicyWebGroupEntryMBean, Serializable {

    /**
     * Variable for storing the value of "SsoServerPolicyWebGroupServerURL".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.2.1.3".
     */
    protected String SsoServerPolicyWebGroupServerURL = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerPolicyWebGroupName".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.2.1.2".
     */
    protected String SsoServerPolicyWebGroupName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerPolicyWebGroupIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.2.1.1".
     */
    protected Integer SsoServerPolicyWebGroupIndex = new Integer(1);

    /**
     * Variable for storing the value of "SsoServerRealmIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.9.1.1".
     */
    protected Integer SsoServerRealmIndex = new Integer(1);


    /**
     * Constructor for the "SsoServerPolicyWebGroupEntry" group.
     */
    public SsoServerPolicyWebGroupEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "SsoServerPolicyWebGroupServerURL" variable.
     */
    public String getSsoServerPolicyWebGroupServerURL() throws SnmpStatusException {
        return SsoServerPolicyWebGroupServerURL;
    }

    /**
     * Getter for the "SsoServerPolicyWebGroupName" variable.
     */
    public String getSsoServerPolicyWebGroupName() throws SnmpStatusException {
        return SsoServerPolicyWebGroupName;
    }

    /**
     * Getter for the "SsoServerPolicyWebGroupIndex" variable.
     */
    public Integer getSsoServerPolicyWebGroupIndex() throws SnmpStatusException {
        return SsoServerPolicyWebGroupIndex;
    }

    /**
     * Getter for the "SsoServerRealmIndex" variable.
     */
    public Integer getSsoServerRealmIndex() throws SnmpStatusException {
        return SsoServerRealmIndex;
    }

}
