package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SsoServerWSSAgentsWSPAgtGrpEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.42.2.230.3.1.1.2.1.22.4.1.
 */
public class SsoServerWSSAgentsWSPAgtGrpEntry implements SsoServerWSSAgentsWSPAgtGrpEntryMBean, Serializable {

    /**
     * Variable for storing the value of "WssAgentsWSPAgtGrpSvcEndPoint".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.22.4.1.4".
     */
    protected String WssAgentsWSPAgtGrpSvcEndPoint = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "WssAgentsWSPAgtGrpProxy".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.22.4.1.3".
     */
    protected String WssAgentsWSPAgtGrpProxy = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "WssAgentsWSPAgtGrpName".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.22.4.1.2".
     */
    protected String WssAgentsWSPAgtGrpName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "WssAgentsWSPAgtGrpIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.22.4.1.1".
     */
    protected Integer WssAgentsWSPAgtGrpIndex = new Integer(1);

    /**
     * Variable for storing the value of "SsoServerRealmIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.9.1.1".
     */
    protected Integer SsoServerRealmIndex = new Integer(1);


    /**
     * Constructor for the "SsoServerWSSAgentsWSPAgtGrpEntry" group.
     */
    public SsoServerWSSAgentsWSPAgtGrpEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "WssAgentsWSPAgtGrpSvcEndPoint" variable.
     */
    public String getWssAgentsWSPAgtGrpSvcEndPoint() throws SnmpStatusException {
        return WssAgentsWSPAgtGrpSvcEndPoint;
    }

    /**
     * Getter for the "WssAgentsWSPAgtGrpProxy" variable.
     */
    public String getWssAgentsWSPAgtGrpProxy() throws SnmpStatusException {
        return WssAgentsWSPAgtGrpProxy;
    }

    /**
     * Getter for the "WssAgentsWSPAgtGrpName" variable.
     */
    public String getWssAgentsWSPAgtGrpName() throws SnmpStatusException {
        return WssAgentsWSPAgtGrpName;
    }

    /**
     * Getter for the "WssAgentsWSPAgtGrpIndex" variable.
     */
    public Integer getWssAgentsWSPAgtGrpIndex() throws SnmpStatusException {
        return WssAgentsWSPAgtGrpIndex;
    }

    /**
     * Getter for the "SsoServerRealmIndex" variable.
     */
    public Integer getSsoServerRealmIndex() throws SnmpStatusException {
        return SsoServerRealmIndex;
    }

}
