package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SsoServerLoggingHdlrEntry" MBean.
 */
public interface SsoServerLoggingHdlrEntryMBean {

    /**
     * Getter for the "SsoServerLoggingHdlrConnFailed" variable.
     */
    public Long getSsoServerLoggingHdlrConnFailed() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerLoggingHdlrConnMade" variable.
     */
    public Long getSsoServerLoggingHdlrConnMade() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerLoggingHdlrConnRqts" variable.
     */
    public Long getSsoServerLoggingHdlrConnRqts() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerLoggingHdlrDroppedCt" variable.
     */
    public Long getSsoServerLoggingHdlrDroppedCt() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerLoggingHdlrFailureCt" variable.
     */
    public Long getSsoServerLoggingHdlrFailureCt() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerLoggingHdlrSuccessCt" variable.
     */
    public Long getSsoServerLoggingHdlrSuccessCt() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerLoggingHdlrRqtCt" variable.
     */
    public Long getSsoServerLoggingHdlrRqtCt() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerLoggingHdlrName" variable.
     */
    public String getSsoServerLoggingHdlrName() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerLoggingHdlrIndex" variable.
     */
    public Integer getSsoServerLoggingHdlrIndex() throws SnmpStatusException;

}
