package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SsoServerLoggingHdlrEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.42.2.230.3.1.1.2.1.12.11.1.
 */
public class SsoServerLoggingHdlrEntry implements SsoServerLoggingHdlrEntryMBean, Serializable {

    /**
     * Variable for storing the value of "SsoServerLoggingHdlrConnFailed".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.12.11.1.9".
     */
    protected Long SsoServerLoggingHdlrConnFailed = new Long(1);

    /**
     * Variable for storing the value of "SsoServerLoggingHdlrConnMade".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.12.11.1.8".
     */
    protected Long SsoServerLoggingHdlrConnMade = new Long(1);

    /**
     * Variable for storing the value of "SsoServerLoggingHdlrConnRqts".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.12.11.1.7".
     */
    protected Long SsoServerLoggingHdlrConnRqts = new Long(1);

    /**
     * Variable for storing the value of "SsoServerLoggingHdlrDroppedCt".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.12.11.1.6".
     */
    protected Long SsoServerLoggingHdlrDroppedCt = new Long(1);

    /**
     * Variable for storing the value of "SsoServerLoggingHdlrFailureCt".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.12.11.1.5".
     */
    protected Long SsoServerLoggingHdlrFailureCt = new Long(1);

    /**
     * Variable for storing the value of "SsoServerLoggingHdlrSuccessCt".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.12.11.1.4".
     */
    protected Long SsoServerLoggingHdlrSuccessCt = new Long(1);

    /**
     * Variable for storing the value of "SsoServerLoggingHdlrRqtCt".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.12.11.1.3".
     */
    protected Long SsoServerLoggingHdlrRqtCt = new Long(1);

    /**
     * Variable for storing the value of "SsoServerLoggingHdlrName".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.12.11.1.2".
     */
    protected String SsoServerLoggingHdlrName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerLoggingHdlrIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.12.11.1.1".
     */
    protected Integer SsoServerLoggingHdlrIndex = new Integer(1);


    /**
     * Constructor for the "SsoServerLoggingHdlrEntry" group.
     */
    public SsoServerLoggingHdlrEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "SsoServerLoggingHdlrConnFailed" variable.
     */
    public Long getSsoServerLoggingHdlrConnFailed() throws SnmpStatusException {
        return SsoServerLoggingHdlrConnFailed;
    }

    /**
     * Getter for the "SsoServerLoggingHdlrConnMade" variable.
     */
    public Long getSsoServerLoggingHdlrConnMade() throws SnmpStatusException {
        return SsoServerLoggingHdlrConnMade;
    }

    /**
     * Getter for the "SsoServerLoggingHdlrConnRqts" variable.
     */
    public Long getSsoServerLoggingHdlrConnRqts() throws SnmpStatusException {
        return SsoServerLoggingHdlrConnRqts;
    }

    /**
     * Getter for the "SsoServerLoggingHdlrDroppedCt" variable.
     */
    public Long getSsoServerLoggingHdlrDroppedCt() throws SnmpStatusException {
        return SsoServerLoggingHdlrDroppedCt;
    }

    /**
     * Getter for the "SsoServerLoggingHdlrFailureCt" variable.
     */
    public Long getSsoServerLoggingHdlrFailureCt() throws SnmpStatusException {
        return SsoServerLoggingHdlrFailureCt;
    }

    /**
     * Getter for the "SsoServerLoggingHdlrSuccessCt" variable.
     */
    public Long getSsoServerLoggingHdlrSuccessCt() throws SnmpStatusException {
        return SsoServerLoggingHdlrSuccessCt;
    }

    /**
     * Getter for the "SsoServerLoggingHdlrRqtCt" variable.
     */
    public Long getSsoServerLoggingHdlrRqtCt() throws SnmpStatusException {
        return SsoServerLoggingHdlrRqtCt;
    }

    /**
     * Getter for the "SsoServerLoggingHdlrName" variable.
     */
    public String getSsoServerLoggingHdlrName() throws SnmpStatusException {
        return SsoServerLoggingHdlrName;
    }

    /**
     * Getter for the "SsoServerLoggingHdlrIndex" variable.
     */
    public Integer getSsoServerLoggingHdlrIndex() throws SnmpStatusException {
        return SsoServerLoggingHdlrIndex;
    }

}
