package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SsoServerSAML1TrustPrtnrsEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.42.2.230.3.1.1.2.1.16.3.1.
 */
public class SsoServerSAML1TrustPrtnrsEntry implements SsoServerSAML1TrustPrtnrsEntryMBean, Serializable {

    /**
     * Variable for storing the value of "SsoServerSAML1TrustPrtnrName".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.16.3.1.2".
     */
    protected String SsoServerSAML1TrustPrtnrName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerSAML1TrustPrtnrIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.16.3.1.1".
     */
    protected Integer SsoServerSAML1TrustPrtnrIndex = new Integer(1);


    /**
     * Constructor for the "SsoServerSAML1TrustPrtnrsEntry" group.
     */
    public SsoServerSAML1TrustPrtnrsEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "SsoServerSAML1TrustPrtnrName" variable.
     */
    public String getSsoServerSAML1TrustPrtnrName() throws SnmpStatusException {
        return SsoServerSAML1TrustPrtnrName;
    }

    /**
     * Getter for the "SsoServerSAML1TrustPrtnrIndex" variable.
     */
    public Integer getSsoServerSAML1TrustPrtnrIndex() throws SnmpStatusException {
        return SsoServerSAML1TrustPrtnrIndex;
    }

}
