package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SsoServerPolicySvc" MBean.
 */
public interface SsoServerPolicySvcMBean {

    /**
     * Getter for the "SsoServerPolicyEvalsOut" variable.
     */
    public Long getSsoServerPolicyEvalsOut() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerPolicyEvalsIn" variable.
     */
    public Long getSsoServerPolicyEvalsIn() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerPolicyStatus" variable.
     */
    public String getSsoServerPolicyStatus() throws SnmpStatusException;

}
