package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SsoServerSitesEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.42.2.230.3.1.1.2.1.8.2.1.
 */
public class SsoServerSitesEntry implements SsoServerSitesEntryMBean, Serializable {

    /**
     * Variable for storing the value of "SsoServerSiteState".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.8.2.1.3".
     */
    protected Integer SsoServerSiteState = new Integer(1);

    /**
     * Variable for storing the value of "SsoServerSiteName".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.8.2.1.2".
     */
    protected String SsoServerSiteName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerSiteId".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.8.2.1.1".
     */
    protected Integer SsoServerSiteId = new Integer(1);


    /**
     * Constructor for the "SsoServerSitesEntry" group.
     */
    public SsoServerSitesEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "SsoServerSiteState" variable.
     */
    public Integer getSsoServerSiteState() throws SnmpStatusException {
        return SsoServerSiteState;
    }

    /**
     * Getter for the "SsoServerSiteName" variable.
     */
    public String getSsoServerSiteName() throws SnmpStatusException {
        return SsoServerSiteName;
    }

    /**
     * Getter for the "SsoServerSiteId" variable.
     */
    public Integer getSsoServerSiteId() throws SnmpStatusException {
        return SsoServerSiteId;
    }

}
