package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import javax.management.MBeanServer;
import com.sun.management.snmp.SnmpString;
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SsoServerIdRepoSvc" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.42.2.230.3.1.1.2.1.15.
 */
public class SsoServerIdRepoSvc implements SsoServerIdRepoSvcMBean, Serializable {

    /**
     * Variable for storing the value of "SsoServerIdRepoSearchCacheHits".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.15.5".
     */
    protected Long SsoServerIdRepoSearchCacheHits = new Long(1);

    /**
     * Variable for storing the value of "SsoServerIdRepoSearchRqts".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.15.4".
     */
    protected Long SsoServerIdRepoSearchRqts = new Long(1);

    /**
     * Variable for storing the value of "SsoServerIdRepoCacheHits".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.15.3".
     */
    protected Long SsoServerIdRepoCacheHits = new Long(1);

    /**
     * Variable for storing the value of "SsoServerIdRepoCacheEntries".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.15.2".
     */
    protected Long SsoServerIdRepoCacheEntries = new Long(1);

    /**
     * Variable for storing the value of "SsoServerIdRepoGetRqts".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.15.1".
     */
    protected Long SsoServerIdRepoGetRqts = new Long(1);


    /**
     * Constructor for the "SsoServerIdRepoSvc" group.
     * If the group contains a table, the entries created through an SNMP SET will not be registered in Java DMK.
     */
    public SsoServerIdRepoSvc(SnmpMib myMib) {
    }


    /**
     * Constructor for the "SsoServerIdRepoSvc" group.
     * If the group contains a table, the entries created through an SNMP SET will be AUTOMATICALLY REGISTERED in Java DMK.
     */
    public SsoServerIdRepoSvc(SnmpMib myMib, MBeanServer server) {
    }

    /**
     * Getter for the "SsoServerIdRepoSearchCacheHits" variable.
     */
    public Long getSsoServerIdRepoSearchCacheHits() throws SnmpStatusException {
        return SsoServerIdRepoSearchCacheHits;
    }

    /**
     * Getter for the "SsoServerIdRepoSearchRqts" variable.
     */
    public Long getSsoServerIdRepoSearchRqts() throws SnmpStatusException {
        return SsoServerIdRepoSearchRqts;
    }

    /**
     * Getter for the "SsoServerIdRepoCacheHits" variable.
     */
    public Long getSsoServerIdRepoCacheHits() throws SnmpStatusException {
        return SsoServerIdRepoCacheHits;
    }

    /**
     * Getter for the "SsoServerIdRepoCacheEntries" variable.
     */
    public Long getSsoServerIdRepoCacheEntries() throws SnmpStatusException {
        return SsoServerIdRepoCacheEntries;
    }

    /**
     * Getter for the "SsoServerIdRepoGetRqts" variable.
     */
    public Long getSsoServerIdRepoGetRqts() throws SnmpStatusException {
        return SsoServerIdRepoGetRqts;
    }

}
