package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SsoServerPolicy22AgentEntry" MBean.
 */
public interface SsoServerPolicy22AgentEntryMBean {

    /**
     * Getter for the "SsoServerPolicy22AgentName" variable.
     */
    public String getSsoServerPolicy22AgentName() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerPolicy22AgentIndex" variable.
     */
    public Integer getSsoServerPolicy22AgentIndex() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerRealmIndex" variable.
     */
    public Integer getSsoServerRealmIndex() throws SnmpStatusException;

}
