package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SsoServerIDFFSvc" MBean.
 */
public interface SsoServerIDFFSvcMBean {

    /**
     * Getter for the "SsoServerIDFFIdLocalSessToken" variable.
     */
    public Long getSsoServerIDFFIdLocalSessToken() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerIDFFIdAuthnRqt" variable.
     */
    public Long getSsoServerIDFFIdAuthnRqt() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerIDFFUserIDSessionList" variable.
     */
    public Long getSsoServerIDFFUserIDSessionList() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerIDFFArtifacts" variable.
     */
    public Long getSsoServerIDFFArtifacts() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerIDFFAssertions" variable.
     */
    public Long getSsoServerIDFFAssertions() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerIDFFStatus" variable.
     */
    public String getSsoServerIDFFStatus() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerIDFFRelayState" variable.
     */
    public Long getSsoServerIDFFRelayState() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerIDFFIdDestn" variable.
     */
    public Long getSsoServerIDFFIdDestn() throws SnmpStatusException;

}
