package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SsoServerPolicyWebAgentEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.1.1.
 */
public class SsoServerPolicyWebAgentEntry implements SsoServerPolicyWebAgentEntryMBean, Serializable {

    /**
     * Variable for storing the value of "SsoServerPolicyWebAgentGroup".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.1.1.5".
     */
    protected String SsoServerPolicyWebAgentGroup = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerPolicyWebAgentAgentURL".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.1.1.4".
     */
    protected String SsoServerPolicyWebAgentAgentURL = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerPolicyWebAgentServerURL".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.1.1.3".
     */
    protected String SsoServerPolicyWebAgentServerURL = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerPolicyWebAgentName".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.1.1.2".
     */
    protected String SsoServerPolicyWebAgentName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerPolicyWebAgentIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.1.1.1".
     */
    protected Integer SsoServerPolicyWebAgentIndex = new Integer(1);

    /**
     * Variable for storing the value of "SsoServerRealmIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.9.1.1".
     */
    protected Integer SsoServerRealmIndex = new Integer(1);


    /**
     * Constructor for the "SsoServerPolicyWebAgentEntry" group.
     */
    public SsoServerPolicyWebAgentEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "SsoServerPolicyWebAgentGroup" variable.
     */
    public String getSsoServerPolicyWebAgentGroup() throws SnmpStatusException {
        return SsoServerPolicyWebAgentGroup;
    }

    /**
     * Getter for the "SsoServerPolicyWebAgentAgentURL" variable.
     */
    public String getSsoServerPolicyWebAgentAgentURL() throws SnmpStatusException {
        return SsoServerPolicyWebAgentAgentURL;
    }

    /**
     * Getter for the "SsoServerPolicyWebAgentServerURL" variable.
     */
    public String getSsoServerPolicyWebAgentServerURL() throws SnmpStatusException {
        return SsoServerPolicyWebAgentServerURL;
    }

    /**
     * Getter for the "SsoServerPolicyWebAgentName" variable.
     */
    public String getSsoServerPolicyWebAgentName() throws SnmpStatusException {
        return SsoServerPolicyWebAgentName;
    }

    /**
     * Getter for the "SsoServerPolicyWebAgentIndex" variable.
     */
    public Integer getSsoServerPolicyWebAgentIndex() throws SnmpStatusException {
        return SsoServerPolicyWebAgentIndex;
    }

    /**
     * Getter for the "SsoServerRealmIndex" variable.
     */
    public Integer getSsoServerRealmIndex() throws SnmpStatusException {
        return SsoServerRealmIndex;
    }

}
