package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SsoServerSAML1EndPointEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.42.2.230.3.1.1.2.1.16.2.1.
 */
public class SsoServerSAML1EndPointEntry implements SsoServerSAML1EndPointEntryMBean, Serializable {

    /**
     * Variable for storing the value of "SsoServerSAML1EndPointRqtFailed".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.16.2.1.6".
     */
    protected Long SsoServerSAML1EndPointRqtFailed = new Long(1);

    /**
     * Variable for storing the value of "SsoServerSAML1EndPointRqtOut".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.16.2.1.5".
     */
    protected Long SsoServerSAML1EndPointRqtOut = new Long(1);

    /**
     * Variable for storing the value of "SsoServerSAML1EndPointRqtIn".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.16.2.1.4".
     */
    protected Long SsoServerSAML1EndPointRqtIn = new Long(1);

    /**
     * Variable for storing the value of "SsoServerSAML1EndPointStatus".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.16.2.1.3".
     */
    protected String SsoServerSAML1EndPointStatus = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerSAML1EndPointName".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.16.2.1.2".
     */
    protected String SsoServerSAML1EndPointName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerSAML1EndPointIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.16.2.1.1".
     */
    protected Integer SsoServerSAML1EndPointIndex = new Integer(1);

    /**
     * Variable for storing the value of "SsoServerSAML1EndPointRqtAborted".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.16.2.1.7".
     */
    protected Long SsoServerSAML1EndPointRqtAborted = new Long(1);


    /**
     * Constructor for the "SsoServerSAML1EndPointEntry" group.
     */
    public SsoServerSAML1EndPointEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "SsoServerSAML1EndPointRqtFailed" variable.
     */
    public Long getSsoServerSAML1EndPointRqtFailed() throws SnmpStatusException {
        return SsoServerSAML1EndPointRqtFailed;
    }

    /**
     * Getter for the "SsoServerSAML1EndPointRqtOut" variable.
     */
    public Long getSsoServerSAML1EndPointRqtOut() throws SnmpStatusException {
        return SsoServerSAML1EndPointRqtOut;
    }

    /**
     * Getter for the "SsoServerSAML1EndPointRqtIn" variable.
     */
    public Long getSsoServerSAML1EndPointRqtIn() throws SnmpStatusException {
        return SsoServerSAML1EndPointRqtIn;
    }

    /**
     * Getter for the "SsoServerSAML1EndPointStatus" variable.
     */
    public String getSsoServerSAML1EndPointStatus() throws SnmpStatusException {
        return SsoServerSAML1EndPointStatus;
    }

    /**
     * Getter for the "SsoServerSAML1EndPointName" variable.
     */
    public String getSsoServerSAML1EndPointName() throws SnmpStatusException {
        return SsoServerSAML1EndPointName;
    }

    /**
     * Getter for the "SsoServerSAML1EndPointIndex" variable.
     */
    public Integer getSsoServerSAML1EndPointIndex() throws SnmpStatusException {
        return SsoServerSAML1EndPointIndex;
    }

    /**
     * Getter for the "SsoServerSAML1EndPointRqtAborted" variable.
     */
    public Long getSsoServerSAML1EndPointRqtAborted() throws SnmpStatusException {
        return SsoServerSAML1EndPointRqtAborted;
    }

}
