package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import javax.management.MBeanServer;
import com.sun.management.snmp.SnmpString;
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SsoServerIDFFSvc" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.42.2.230.3.1.1.2.1.20.
 */
public class SsoServerIDFFSvc implements SsoServerIDFFSvcMBean, Serializable {

    /**
     * Variable for storing the value of "SsoServerIDFFIdLocalSessToken".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.20.6".
     */
    protected Long SsoServerIDFFIdLocalSessToken = new Long(1);

    /**
     * Variable for storing the value of "SsoServerIDFFIdAuthnRqt".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.20.5".
     */
    protected Long SsoServerIDFFIdAuthnRqt = new Long(1);

    /**
     * Variable for storing the value of "SsoServerIDFFUserIDSessionList".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.20.4".
     */
    protected Long SsoServerIDFFUserIDSessionList = new Long(1);

    /**
     * Variable for storing the value of "SsoServerIDFFArtifacts".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.20.3".
     */
    protected Long SsoServerIDFFArtifacts = new Long(1);

    /**
     * Variable for storing the value of "SsoServerIDFFAssertions".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.20.2".
     */
    protected Long SsoServerIDFFAssertions = new Long(1);

    /**
     * Variable for storing the value of "SsoServerIDFFStatus".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.20.1".
     */
    protected String SsoServerIDFFStatus = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerIDFFRelayState".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.20.8".
     */
    protected Long SsoServerIDFFRelayState = new Long(1);

    /**
     * Variable for storing the value of "SsoServerIDFFIdDestn".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.20.7".
     */
    protected Long SsoServerIDFFIdDestn = new Long(1);


    /**
     * Constructor for the "SsoServerIDFFSvc" group.
     * If the group contains a table, the entries created through an SNMP SET will not be registered in Java DMK.
     */
    public SsoServerIDFFSvc(SnmpMib myMib) {
    }


    /**
     * Constructor for the "SsoServerIDFFSvc" group.
     * If the group contains a table, the entries created through an SNMP SET will be AUTOMATICALLY REGISTERED in Java DMK.
     */
    public SsoServerIDFFSvc(SnmpMib myMib, MBeanServer server) {
    }

    /**
     * Getter for the "SsoServerIDFFIdLocalSessToken" variable.
     */
    public Long getSsoServerIDFFIdLocalSessToken() throws SnmpStatusException {
        return SsoServerIDFFIdLocalSessToken;
    }

    /**
     * Getter for the "SsoServerIDFFIdAuthnRqt" variable.
     */
    public Long getSsoServerIDFFIdAuthnRqt() throws SnmpStatusException {
        return SsoServerIDFFIdAuthnRqt;
    }

    /**
     * Getter for the "SsoServerIDFFUserIDSessionList" variable.
     */
    public Long getSsoServerIDFFUserIDSessionList() throws SnmpStatusException {
        return SsoServerIDFFUserIDSessionList;
    }

    /**
     * Getter for the "SsoServerIDFFArtifacts" variable.
     */
    public Long getSsoServerIDFFArtifacts() throws SnmpStatusException {
        return SsoServerIDFFArtifacts;
    }

    /**
     * Getter for the "SsoServerIDFFAssertions" variable.
     */
    public Long getSsoServerIDFFAssertions() throws SnmpStatusException {
        return SsoServerIDFFAssertions;
    }

    /**
     * Getter for the "SsoServerIDFFStatus" variable.
     */
    public String getSsoServerIDFFStatus() throws SnmpStatusException {
        return SsoServerIDFFStatus;
    }

    /**
     * Getter for the "SsoServerIDFFRelayState" variable.
     */
    public Long getSsoServerIDFFRelayState() throws SnmpStatusException {
        return SsoServerIDFFRelayState;
    }

    /**
     * Getter for the "SsoServerIDFFIdDestn" variable.
     */
    public Long getSsoServerIDFFIdDestn() throws SnmpStatusException {
        return SsoServerIDFFIdDestn;
    }

}
