package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SsoServerSAML2IDPEntry" MBean.
 */
public interface SsoServerSAML2IDPEntryMBean {

    /**
     * Getter for the "SsoServerSAML2IDPArtifactsIssued" variable.
     */
    public Long getSsoServerSAML2IDPArtifactsIssued() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML2IDPAssertionsIssued" variable.
     */
    public Long getSsoServerSAML2IDPAssertionsIssued() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML2IDPInvalRqtsRcvd" variable.
     */
    public Long getSsoServerSAML2IDPInvalRqtsRcvd() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML2IDPRqtsRcvd" variable.
     */
    public Long getSsoServerSAML2IDPRqtsRcvd() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML2IDPName" variable.
     */
    public String getSsoServerSAML2IDPName() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML2IDPIndex" variable.
     */
    public Integer getSsoServerSAML2IDPIndex() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML2IDPArtifactsInCache" variable.
     */
    public Long getSsoServerSAML2IDPArtifactsInCache() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML2IDPAssertionsInCache" variable.
     */
    public Long getSsoServerSAML2IDPAssertionsInCache() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerRealmIndex" variable.
     */
    public Integer getSsoServerRealmIndex() throws SnmpStatusException;

}
