package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SsoServerSessSvc" MBean.
 */
public interface SsoServerSessSvcMBean {

    /**
     * Getter for the "SsoServerSessAveSessSize" variable.
     */
    public Integer getSsoServerSessAveSessSize() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSessNotifListnrCount" variable.
     */
    public Long getSsoServerSessNotifListnrCount() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSessNotifCount" variable.
     */
    public Long getSsoServerSessNotifCount() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSessValidationsCount" variable.
     */
    public Long getSsoServerSessValidationsCount() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSessCreatedCount" variable.
     */
    public Long getSsoServerSessCreatedCount() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSessActiveCount" variable.
     */
    public Long getSsoServerSessActiveCount() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSessSFOBroker" variable.
     */
    public String getSsoServerSessSFOBroker() throws SnmpStatusException;

}
