package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SsoServerSAML1CacheEntry" MBean.
 */
public interface SsoServerSAML1CacheEntryMBean {

    /**
     * Getter for the "SsoServerSAML1CacheMisses" variable.
     */
    public Long getSsoServerSAML1CacheMisses() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML1CacheHits" variable.
     */
    public Long getSsoServerSAML1CacheHits() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML1CacheWrites" variable.
     */
    public Long getSsoServerSAML1CacheWrites() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML1CacheReads" variable.
     */
    public Long getSsoServerSAML1CacheReads() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML1CacheName" variable.
     */
    public String getSsoServerSAML1CacheName() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML1CacheIndex" variable.
     */
    public Integer getSsoServerSAML1CacheIndex() throws SnmpStatusException;

}
