package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SsoServerSiteMapEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.42.2.230.3.1.1.2.1.8.3.1.
 */
public class SsoServerSiteMapEntry implements SsoServerSiteMapEntryMBean, Serializable {

    /**
     * Variable for storing the value of "SsoServerMapServerURL".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.8.3.1.5".
     */
    protected String SsoServerMapServerURL = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerMapSiteName".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.8.3.1.4".
     */
    protected String SsoServerMapSiteName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerMapId".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.8.3.1.3".
     */
    protected String SsoServerMapId = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerSiteMapId".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.8.3.1.2".
     */
    protected Integer SsoServerSiteMapId = new Integer(1);

    /**
     * Variable for storing the value of "SsoServerSiteMapIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.8.3.1.1".
     */
    protected Integer SsoServerSiteMapIndex = new Integer(1);


    /**
     * Constructor for the "SsoServerSiteMapEntry" group.
     */
    public SsoServerSiteMapEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "SsoServerMapServerURL" variable.
     */
    public String getSsoServerMapServerURL() throws SnmpStatusException {
        return SsoServerMapServerURL;
    }

    /**
     * Getter for the "SsoServerMapSiteName" variable.
     */
    public String getSsoServerMapSiteName() throws SnmpStatusException {
        return SsoServerMapSiteName;
    }

    /**
     * Getter for the "SsoServerMapId" variable.
     */
    public String getSsoServerMapId() throws SnmpStatusException {
        return SsoServerMapId;
    }

    /**
     * Getter for the "SsoServerSiteMapId" variable.
     */
    public Integer getSsoServerSiteMapId() throws SnmpStatusException {
        return SsoServerSiteMapId;
    }

    /**
     * Getter for the "SsoServerSiteMapIndex" variable.
     */
    public Integer getSsoServerSiteMapIndex() throws SnmpStatusException {
        return SsoServerSiteMapIndex;
    }

}
