package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SsoServerSitesEntry" MBean.
 */
public interface SsoServerSitesEntryMBean {

    /**
     * Getter for the "SsoServerSiteState" variable.
     */
    public Integer getSsoServerSiteState() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSiteName" variable.
     */
    public String getSsoServerSiteName() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSiteId" variable.
     */
    public Integer getSsoServerSiteId() throws SnmpStatusException;

}
