package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import javax.management.MBeanServer;
import com.sun.management.snmp.SnmpString;
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SsoServerAuthSvc" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.42.2.230.3.1.1.2.1.10.
 */
public class SsoServerAuthSvc implements SsoServerAuthSvcMBean, Serializable {

    /**
     * Variable for storing the value of "SsoServerAuthModulesTable".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.10.5".
     */
    protected TableSsoServerAuthModulesTable SsoServerAuthModulesTable;

    /**
     * Variable for storing the value of "SsoServerAuthFailureRate".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.10.4".
     */
    protected Long SsoServerAuthFailureRate = new Long(1);

    /**
     * Variable for storing the value of "SsoServerAuthSuccessRate".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.10.3".
     */
    protected Long SsoServerAuthSuccessRate = new Long(1);

    /**
     * Variable for storing the value of "SsoServerAuthFailureCount".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.10.2".
     */
    protected Long SsoServerAuthFailureCount = new Long(1);

    /**
     * Variable for storing the value of "SsoServerAuthSuccessCount".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.10.1".
     */
    protected Long SsoServerAuthSuccessCount = new Long(1);


    /**
     * Constructor for the "SsoServerAuthSvc" group.
     * If the group contains a table, the entries created through an SNMP SET will not be registered in Java DMK.
     */
    public SsoServerAuthSvc(SnmpMib myMib) {
        SsoServerAuthModulesTable = new TableSsoServerAuthModulesTable (myMib);
    }


    /**
     * Constructor for the "SsoServerAuthSvc" group.
     * If the group contains a table, the entries created through an SNMP SET will be AUTOMATICALLY REGISTERED in Java DMK.
     */
    public SsoServerAuthSvc(SnmpMib myMib, MBeanServer server) {
        SsoServerAuthModulesTable = new TableSsoServerAuthModulesTable (myMib, server);
    }

    /**
     * Access the "SsoServerAuthModulesTable" variable.
     */
    public TableSsoServerAuthModulesTable accessSsoServerAuthModulesTable() throws SnmpStatusException {
        return SsoServerAuthModulesTable;
    }

    /**
     * Access the "SsoServerAuthModulesTable" variable as a bean indexed property.
     */
    public SsoServerAuthModulesEntryMBean[] getSsoServerAuthModulesTable() throws SnmpStatusException {
        return SsoServerAuthModulesTable.getEntries();
    }

    /**
     * Getter for the "SsoServerAuthFailureRate" variable.
     */
    public Long getSsoServerAuthFailureRate() throws SnmpStatusException {
        return SsoServerAuthFailureRate;
    }

    /**
     * Getter for the "SsoServerAuthSuccessRate" variable.
     */
    public Long getSsoServerAuthSuccessRate() throws SnmpStatusException {
        return SsoServerAuthSuccessRate;
    }

    /**
     * Getter for the "SsoServerAuthFailureCount" variable.
     */
    public Long getSsoServerAuthFailureCount() throws SnmpStatusException {
        return SsoServerAuthFailureCount;
    }

    /**
     * Getter for the "SsoServerAuthSuccessCount" variable.
     */
    public Long getSsoServerAuthSuccessCount() throws SnmpStatusException {
        return SsoServerAuthSuccessCount;
    }

}
