package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SsoServerPolicyWebGroupEntry" MBean.
 */
public interface SsoServerPolicyWebGroupEntryMBean {

    /**
     * Getter for the "SsoServerPolicyWebGroupServerURL" variable.
     */
    public String getSsoServerPolicyWebGroupServerURL() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerPolicyWebGroupName" variable.
     */
    public String getSsoServerPolicyWebGroupName() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerPolicyWebGroupIndex" variable.
     */
    public Integer getSsoServerPolicyWebGroupIndex() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerRealmIndex" variable.
     */
    public Integer getSsoServerRealmIndex() throws SnmpStatusException;

}
