package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SsoServerSAML2SPEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.42.2.230.3.1.1.2.1.17.7.1.
 */
public class SsoServerSAML2SPEntry implements SsoServerSAML2SPEntryMBean, Serializable {

    /**
     * Variable for storing the value of "SsoServerSAML2SPInvalidArtifactsRcvd".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.17.7.1.5".
     */
    protected Long SsoServerSAML2SPInvalidArtifactsRcvd = new Long(1);

    /**
     * Variable for storing the value of "SsoServerSAML2SPValidAssertionsRcvd".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.17.7.1.4".
     */
    protected Long SsoServerSAML2SPValidAssertionsRcvd = new Long(1);

    /**
     * Variable for storing the value of "SsoServerSAML2SPRqtsSent".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.17.7.1.3".
     */
    protected Long SsoServerSAML2SPRqtsSent = new Long(1);

    /**
     * Variable for storing the value of "SsoServerSAML2SPName".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.17.7.1.2".
     */
    protected String SsoServerSAML2SPName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerSAML2SPIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.17.7.1.1".
     */
    protected Integer SsoServerSAML2SPIndex = new Integer(1);

    /**
     * Variable for storing the value of "SsoServerRealmIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.9.1.1".
     */
    protected Integer SsoServerRealmIndex = new Integer(1);


    /**
     * Constructor for the "SsoServerSAML2SPEntry" group.
     */
    public SsoServerSAML2SPEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "SsoServerSAML2SPInvalidArtifactsRcvd" variable.
     */
    public Long getSsoServerSAML2SPInvalidArtifactsRcvd() throws SnmpStatusException {
        return SsoServerSAML2SPInvalidArtifactsRcvd;
    }

    /**
     * Getter for the "SsoServerSAML2SPValidAssertionsRcvd" variable.
     */
    public Long getSsoServerSAML2SPValidAssertionsRcvd() throws SnmpStatusException {
        return SsoServerSAML2SPValidAssertionsRcvd;
    }

    /**
     * Getter for the "SsoServerSAML2SPRqtsSent" variable.
     */
    public Long getSsoServerSAML2SPRqtsSent() throws SnmpStatusException {
        return SsoServerSAML2SPRqtsSent;
    }

    /**
     * Getter for the "SsoServerSAML2SPName" variable.
     */
    public String getSsoServerSAML2SPName() throws SnmpStatusException {
        return SsoServerSAML2SPName;
    }

    /**
     * Getter for the "SsoServerSAML2SPIndex" variable.
     */
    public Integer getSsoServerSAML2SPIndex() throws SnmpStatusException {
        return SsoServerSAML2SPIndex;
    }

    /**
     * Getter for the "SsoServerRealmIndex" variable.
     */
    public Integer getSsoServerRealmIndex() throws SnmpStatusException {
        return SsoServerRealmIndex;
    }

}
