package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SsoServerPolicyJ2EEAgentEntry" MBean.
 */
public interface SsoServerPolicyJ2EEAgentEntryMBean {

    /**
     * Getter for the "SsoServerPolicyJ2EEAgentGroup" variable.
     */
    public String getSsoServerPolicyJ2EEAgentGroup() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerPolicyJ2EEAgentAgentURL" variable.
     */
    public String getSsoServerPolicyJ2EEAgentAgentURL() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerPolicyJ2EEAgentServerURL" variable.
     */
    public String getSsoServerPolicyJ2EEAgentServerURL() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerPolicyJ2EEAgentName" variable.
     */
    public String getSsoServerPolicyJ2EEAgentName() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerPolicyJ2EEAgentIndex" variable.
     */
    public Integer getSsoServerPolicyJ2EEAgentIndex() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerRealmIndex" variable.
     */
    public Integer getSsoServerRealmIndex() throws SnmpStatusException;

}
