package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SsoServerPolicyJ2EEGroupEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.4.1.
 */
public class SsoServerPolicyJ2EEGroupEntry implements SsoServerPolicyJ2EEGroupEntryMBean, Serializable {

    /**
     * Variable for storing the value of "SsoServerPolicyJ2EEGroupServerURL".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.4.1.3".
     */
    protected String SsoServerPolicyJ2EEGroupServerURL = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerPolicyJ2EEGroupName".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.4.1.2".
     */
    protected String SsoServerPolicyJ2EEGroupName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerPolicyJ2EEGroupIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.4.1.1".
     */
    protected Integer SsoServerPolicyJ2EEGroupIndex = new Integer(1);

    /**
     * Variable for storing the value of "SsoServerRealmIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.9.1.1".
     */
    protected Integer SsoServerRealmIndex = new Integer(1);


    /**
     * Constructor for the "SsoServerPolicyJ2EEGroupEntry" group.
     */
    public SsoServerPolicyJ2EEGroupEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "SsoServerPolicyJ2EEGroupServerURL" variable.
     */
    public String getSsoServerPolicyJ2EEGroupServerURL() throws SnmpStatusException {
        return SsoServerPolicyJ2EEGroupServerURL;
    }

    /**
     * Getter for the "SsoServerPolicyJ2EEGroupName" variable.
     */
    public String getSsoServerPolicyJ2EEGroupName() throws SnmpStatusException {
        return SsoServerPolicyJ2EEGroupName;
    }

    /**
     * Getter for the "SsoServerPolicyJ2EEGroupIndex" variable.
     */
    public Integer getSsoServerPolicyJ2EEGroupIndex() throws SnmpStatusException {
        return SsoServerPolicyJ2EEGroupIndex;
    }

    /**
     * Getter for the "SsoServerRealmIndex" variable.
     */
    public Integer getSsoServerRealmIndex() throws SnmpStatusException {
        return SsoServerRealmIndex;
    }

}
