package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SsoServerWSSAgentsSTSAgtGrpEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.42.2.230.3.1.1.2.1.22.6.1.
 */
public class SsoServerWSSAgentsSTSAgtGrpEntry implements SsoServerWSSAgentsSTSAgtGrpEntryMBean, Serializable {

    /**
     * Variable for storing the value of "WssAgentsSTSAgtGrpSvcMEXEndPoint".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.22.6.1.4".
     */
    protected String WssAgentsSTSAgtGrpSvcMEXEndPoint = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "WssAgentsSTSAgtGrpSvcEndPoint".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.22.6.1.3".
     */
    protected String WssAgentsSTSAgtGrpSvcEndPoint = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "WssAgentsSTSAgtGrpName".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.22.6.1.2".
     */
    protected String WssAgentsSTSAgtGrpName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "WssAgentsSTSAgtGrpIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.22.6.1.1".
     */
    protected Integer WssAgentsSTSAgtGrpIndex = new Integer(1);

    /**
     * Variable for storing the value of "SsoServerRealmIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.9.1.1".
     */
    protected Integer SsoServerRealmIndex = new Integer(1);


    /**
     * Constructor for the "SsoServerWSSAgentsSTSAgtGrpEntry" group.
     */
    public SsoServerWSSAgentsSTSAgtGrpEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "WssAgentsSTSAgtGrpSvcMEXEndPoint" variable.
     */
    public String getWssAgentsSTSAgtGrpSvcMEXEndPoint() throws SnmpStatusException {
        return WssAgentsSTSAgtGrpSvcMEXEndPoint;
    }

    /**
     * Getter for the "WssAgentsSTSAgtGrpSvcEndPoint" variable.
     */
    public String getWssAgentsSTSAgtGrpSvcEndPoint() throws SnmpStatusException {
        return WssAgentsSTSAgtGrpSvcEndPoint;
    }

    /**
     * Getter for the "WssAgentsSTSAgtGrpName" variable.
     */
    public String getWssAgentsSTSAgtGrpName() throws SnmpStatusException {
        return WssAgentsSTSAgtGrpName;
    }

    /**
     * Getter for the "WssAgentsSTSAgtGrpIndex" variable.
     */
    public Integer getWssAgentsSTSAgtGrpIndex() throws SnmpStatusException {
        return WssAgentsSTSAgtGrpIndex;
    }

    /**
     * Getter for the "SsoServerRealmIndex" variable.
     */
    public Integer getSsoServerRealmIndex() throws SnmpStatusException {
        return SsoServerRealmIndex;
    }

}
