package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SsoServerSAML1EndPointEntry" MBean.
 */
public interface SsoServerSAML1EndPointEntryMBean {

    /**
     * Getter for the "SsoServerSAML1EndPointRqtFailed" variable.
     */
    public Long getSsoServerSAML1EndPointRqtFailed() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML1EndPointRqtOut" variable.
     */
    public Long getSsoServerSAML1EndPointRqtOut() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML1EndPointRqtIn" variable.
     */
    public Long getSsoServerSAML1EndPointRqtIn() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML1EndPointStatus" variable.
     */
    public String getSsoServerSAML1EndPointStatus() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML1EndPointName" variable.
     */
    public String getSsoServerSAML1EndPointName() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML1EndPointIndex" variable.
     */
    public Integer getSsoServerSAML1EndPointIndex() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML1EndPointRqtAborted" variable.
     */
    public Long getSsoServerSAML1EndPointRqtAborted() throws SnmpStatusException;

}
