package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SsoServerPolicyWebAgentEntry" MBean.
 */
public interface SsoServerPolicyWebAgentEntryMBean {

    /**
     * Getter for the "SsoServerPolicyWebAgentGroup" variable.
     */
    public String getSsoServerPolicyWebAgentGroup() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerPolicyWebAgentAgentURL" variable.
     */
    public String getSsoServerPolicyWebAgentAgentURL() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerPolicyWebAgentServerURL" variable.
     */
    public String getSsoServerPolicyWebAgentServerURL() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerPolicyWebAgentName" variable.
     */
    public String getSsoServerPolicyWebAgentName() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerPolicyWebAgentIndex" variable.
     */
    public Integer getSsoServerPolicyWebAgentIndex() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerRealmIndex" variable.
     */
    public Integer getSsoServerRealmIndex() throws SnmpStatusException;

}
