package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SsoServerIdRepoSvc" MBean.
 */
public interface SsoServerIdRepoSvcMBean {

    /**
     * Getter for the "SsoServerIdRepoSearchCacheHits" variable.
     */
    public Long getSsoServerIdRepoSearchCacheHits() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerIdRepoSearchRqts" variable.
     */
    public Long getSsoServerIdRepoSearchRqts() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerIdRepoCacheHits" variable.
     */
    public Long getSsoServerIdRepoCacheHits() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerIdRepoCacheEntries" variable.
     */
    public Long getSsoServerIdRepoCacheEntries() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerIdRepoGetRqts" variable.
     */
    public Long getSsoServerIdRepoGetRqts() throws SnmpStatusException;

}
