package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SsoServerSiteMapEntry" MBean.
 */
public interface SsoServerSiteMapEntryMBean {

    /**
     * Getter for the "SsoServerMapServerURL" variable.
     */
    public String getSsoServerMapServerURL() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerMapSiteName" variable.
     */
    public String getSsoServerMapSiteName() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerMapId" variable.
     */
    public String getSsoServerMapId() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSiteMapId" variable.
     */
    public Integer getSsoServerSiteMapId() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSiteMapIndex" variable.
     */
    public Integer getSsoServerSiteMapIndex() throws SnmpStatusException;

}
