package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SsoServerSvcMgmtSvc" MBean.
 */
public interface SsoServerSvcMgmtSvcMBean {

    /**
     * Getter for the "SsoServerSvcMgmtRepositorySSL" variable.
     */
    public String getSsoServerSvcMgmtRepositorySSL() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSvcMgmtRepositoryOrgDN" variable.
     */
    public String getSsoServerSvcMgmtRepositoryOrgDN() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSvcMgmtRepositoryBindDN" variable.
     */
    public String getSsoServerSvcMgmtRepositoryBindDN() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSvcMgmtRepositoryHostPort" variable.
     */
    public String getSsoServerSvcMgmtRepositoryHostPort() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSvcMgmtRepositoryType" variable.
     */
    public String getSsoServerSvcMgmtRepositoryType() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSvcMgmtStatus" variable.
     */
    public String getSsoServerSvcMgmtStatus() throws SnmpStatusException;

}
