package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SsoServerSAML2IDPEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.42.2.230.3.1.1.2.1.17.6.1.
 */
public class SsoServerSAML2IDPEntry implements SsoServerSAML2IDPEntryMBean, Serializable {

    /**
     * Variable for storing the value of "SsoServerSAML2IDPArtifactsIssued".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.17.6.1.6".
     */
    protected Long SsoServerSAML2IDPArtifactsIssued = new Long(1);

    /**
     * Variable for storing the value of "SsoServerSAML2IDPAssertionsIssued".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.17.6.1.5".
     */
    protected Long SsoServerSAML2IDPAssertionsIssued = new Long(1);

    /**
     * Variable for storing the value of "SsoServerSAML2IDPInvalRqtsRcvd".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.17.6.1.4".
     */
    protected Long SsoServerSAML2IDPInvalRqtsRcvd = new Long(1);

    /**
     * Variable for storing the value of "SsoServerSAML2IDPRqtsRcvd".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.17.6.1.3".
     */
    protected Long SsoServerSAML2IDPRqtsRcvd = new Long(1);

    /**
     * Variable for storing the value of "SsoServerSAML2IDPName".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.17.6.1.2".
     */
    protected String SsoServerSAML2IDPName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerSAML2IDPIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.17.6.1.1".
     */
    protected Integer SsoServerSAML2IDPIndex = new Integer(1);

    /**
     * Variable for storing the value of "SsoServerSAML2IDPArtifactsInCache".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.17.6.1.8".
     */
    protected Long SsoServerSAML2IDPArtifactsInCache = new Long(1);

    /**
     * Variable for storing the value of "SsoServerSAML2IDPAssertionsInCache".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.17.6.1.7".
     */
    protected Long SsoServerSAML2IDPAssertionsInCache = new Long(1);

    /**
     * Variable for storing the value of "SsoServerRealmIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.9.1.1".
     */
    protected Integer SsoServerRealmIndex = new Integer(1);


    /**
     * Constructor for the "SsoServerSAML2IDPEntry" group.
     */
    public SsoServerSAML2IDPEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "SsoServerSAML2IDPArtifactsIssued" variable.
     */
    public Long getSsoServerSAML2IDPArtifactsIssued() throws SnmpStatusException {
        return SsoServerSAML2IDPArtifactsIssued;
    }

    /**
     * Getter for the "SsoServerSAML2IDPAssertionsIssued" variable.
     */
    public Long getSsoServerSAML2IDPAssertionsIssued() throws SnmpStatusException {
        return SsoServerSAML2IDPAssertionsIssued;
    }

    /**
     * Getter for the "SsoServerSAML2IDPInvalRqtsRcvd" variable.
     */
    public Long getSsoServerSAML2IDPInvalRqtsRcvd() throws SnmpStatusException {
        return SsoServerSAML2IDPInvalRqtsRcvd;
    }

    /**
     * Getter for the "SsoServerSAML2IDPRqtsRcvd" variable.
     */
    public Long getSsoServerSAML2IDPRqtsRcvd() throws SnmpStatusException {
        return SsoServerSAML2IDPRqtsRcvd;
    }

    /**
     * Getter for the "SsoServerSAML2IDPName" variable.
     */
    public String getSsoServerSAML2IDPName() throws SnmpStatusException {
        return SsoServerSAML2IDPName;
    }

    /**
     * Getter for the "SsoServerSAML2IDPIndex" variable.
     */
    public Integer getSsoServerSAML2IDPIndex() throws SnmpStatusException {
        return SsoServerSAML2IDPIndex;
    }

    /**
     * Getter for the "SsoServerSAML2IDPArtifactsInCache" variable.
     */
    public Long getSsoServerSAML2IDPArtifactsInCache() throws SnmpStatusException {
        return SsoServerSAML2IDPArtifactsInCache;
    }

    /**
     * Getter for the "SsoServerSAML2IDPAssertionsInCache" variable.
     */
    public Long getSsoServerSAML2IDPAssertionsInCache() throws SnmpStatusException {
        return SsoServerSAML2IDPAssertionsInCache;
    }

    /**
     * Getter for the "SsoServerRealmIndex" variable.
     */
    public Integer getSsoServerRealmIndex() throws SnmpStatusException {
        return SsoServerRealmIndex;
    }

}
