package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SsoServerPolicyJ2EEAgentEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.3.1.
 */
public class SsoServerPolicyJ2EEAgentEntry implements SsoServerPolicyJ2EEAgentEntryMBean, Serializable {

    /**
     * Variable for storing the value of "SsoServerPolicyJ2EEAgentGroup".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.3.1.5".
     */
    protected String SsoServerPolicyJ2EEAgentGroup = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerPolicyJ2EEAgentAgentURL".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.3.1.4".
     */
    protected String SsoServerPolicyJ2EEAgentAgentURL = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerPolicyJ2EEAgentServerURL".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.3.1.3".
     */
    protected String SsoServerPolicyJ2EEAgentServerURL = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerPolicyJ2EEAgentName".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.3.1.2".
     */
    protected String SsoServerPolicyJ2EEAgentName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerPolicyJ2EEAgentIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.21.3.1.1".
     */
    protected Integer SsoServerPolicyJ2EEAgentIndex = new Integer(1);

    /**
     * Variable for storing the value of "SsoServerRealmIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.9.1.1".
     */
    protected Integer SsoServerRealmIndex = new Integer(1);


    /**
     * Constructor for the "SsoServerPolicyJ2EEAgentEntry" group.
     */
    public SsoServerPolicyJ2EEAgentEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "SsoServerPolicyJ2EEAgentGroup" variable.
     */
    public String getSsoServerPolicyJ2EEAgentGroup() throws SnmpStatusException {
        return SsoServerPolicyJ2EEAgentGroup;
    }

    /**
     * Getter for the "SsoServerPolicyJ2EEAgentAgentURL" variable.
     */
    public String getSsoServerPolicyJ2EEAgentAgentURL() throws SnmpStatusException {
        return SsoServerPolicyJ2EEAgentAgentURL;
    }

    /**
     * Getter for the "SsoServerPolicyJ2EEAgentServerURL" variable.
     */
    public String getSsoServerPolicyJ2EEAgentServerURL() throws SnmpStatusException {
        return SsoServerPolicyJ2EEAgentServerURL;
    }

    /**
     * Getter for the "SsoServerPolicyJ2EEAgentName" variable.
     */
    public String getSsoServerPolicyJ2EEAgentName() throws SnmpStatusException {
        return SsoServerPolicyJ2EEAgentName;
    }

    /**
     * Getter for the "SsoServerPolicyJ2EEAgentIndex" variable.
     */
    public Integer getSsoServerPolicyJ2EEAgentIndex() throws SnmpStatusException {
        return SsoServerPolicyJ2EEAgentIndex;
    }

    /**
     * Getter for the "SsoServerRealmIndex" variable.
     */
    public Integer getSsoServerRealmIndex() throws SnmpStatusException {
        return SsoServerRealmIndex;
    }

}
