package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SsoServerSAML2Svc" MBean.
 */
public interface SsoServerSAML2SvcMBean {

    /**
     * Access the "SsoServerSAML2IDPTable" variable.
     */
    public TableSsoServerSAML2IDPTable accessSsoServerSAML2IDPTable() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML2RemoteIDPCount" variable.
     */
    public Long getSsoServerSAML2RemoteIDPCount() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML2HostedIDPCount" variable.
     */
    public Long getSsoServerSAML2HostedIDPCount() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML2FedSessionCount" variable.
     */
    public Long getSsoServerSAML2FedSessionCount() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML2IDPSessionCount" variable.
     */
    public Long getSsoServerSAML2IDPSessionCount() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerSAML2Status" variable.
     */
    public String getSsoServerSAML2Status() throws SnmpStatusException;

    /**
     * Access the "SsoServerSAML2SPTable" variable.
     */
    public TableSsoServerSAML2SPTable accessSsoServerSAML2SPTable() throws SnmpStatusException;

}
