package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SsoServerWSSAgentsWSCAgtGrpEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.42.2.230.3.1.1.2.1.22.2.1.
 */
public class SsoServerWSSAgentsWSCAgtGrpEntry implements SsoServerWSSAgentsWSCAgtGrpEntryMBean, Serializable {

    /**
     * Variable for storing the value of "WssAgentsWSCAgtGrpSvcEndPoint".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.22.2.1.4".
     */
    protected String WssAgentsWSCAgtGrpSvcEndPoint = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "WssAgentsWSCAgtGrpProxy".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.22.2.1.3".
     */
    protected String WssAgentsWSCAgtGrpProxy = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "WssAgentsWSCAgtGrpName".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.22.2.1.2".
     */
    protected String WssAgentsWSCAgtGrpName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "WssAgentsWSCAgtGrpIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.22.2.1.1".
     */
    protected Integer WssAgentsWSCAgtGrpIndex = new Integer(1);

    /**
     * Variable for storing the value of "SsoServerRealmIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.9.1.1".
     */
    protected Integer SsoServerRealmIndex = new Integer(1);


    /**
     * Constructor for the "SsoServerWSSAgentsWSCAgtGrpEntry" group.
     */
    public SsoServerWSSAgentsWSCAgtGrpEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "WssAgentsWSCAgtGrpSvcEndPoint" variable.
     */
    public String getWssAgentsWSCAgtGrpSvcEndPoint() throws SnmpStatusException {
        return WssAgentsWSCAgtGrpSvcEndPoint;
    }

    /**
     * Getter for the "WssAgentsWSCAgtGrpProxy" variable.
     */
    public String getWssAgentsWSCAgtGrpProxy() throws SnmpStatusException {
        return WssAgentsWSCAgtGrpProxy;
    }

    /**
     * Getter for the "WssAgentsWSCAgtGrpName" variable.
     */
    public String getWssAgentsWSCAgtGrpName() throws SnmpStatusException {
        return WssAgentsWSCAgtGrpName;
    }

    /**
     * Getter for the "WssAgentsWSCAgtGrpIndex" variable.
     */
    public Integer getWssAgentsWSCAgtGrpIndex() throws SnmpStatusException {
        return WssAgentsWSCAgtGrpIndex;
    }

    /**
     * Getter for the "SsoServerRealmIndex" variable.
     */
    public Integer getSsoServerRealmIndex() throws SnmpStatusException {
        return SsoServerRealmIndex;
    }

}
