package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SsoServerLoggingSvc" MBean.
 */
public interface SsoServerLoggingSvcMBean {

    /**
     * Getter for the "SsoServerLoggingLoggers" variable.
     */
    public Integer getSsoServerLoggingLoggers() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerLoggingBufferSize" variable.
     */
    public Long getSsoServerLoggingBufferSize() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerLoggingBufferTime" variable.
     */
    public Long getSsoServerLoggingBufferTime() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerLoggingTimeBuffering" variable.
     */
    public String getSsoServerLoggingTimeBuffering() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerLoggingSecure" variable.
     */
    public String getSsoServerLoggingSecure() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerLoggingNumHistFiles" variable.
     */
    public Long getSsoServerLoggingNumHistFiles() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerLoggingMaxLogSize" variable.
     */
    public Long getSsoServerLoggingMaxLogSize() throws SnmpStatusException;

    /**
     * Access the "SsoServerLoggingHdlrTable" variable.
     */
    public TableSsoServerLoggingHdlrTable accessSsoServerLoggingHdlrTable() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerLoggingLocation" variable.
     */
    public String getSsoServerLoggingLocation() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerLoggingType" variable.
     */
    public String getSsoServerLoggingType() throws SnmpStatusException;

    /**
     * Getter for the "SsoServerLoggingRecsRejected" variable.
     */
    public Long getSsoServerLoggingRecsRejected() throws SnmpStatusException;

}
