package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SsoServerServerEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.42.2.230.3.1.1.2.1.8.1.1.
 */
public class SsoServerServerEntry implements SsoServerServerEntryMBean, Serializable {

    /**
     * Variable for storing the value of "SsoServerServerStatus".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.8.1.1.5".
     */
    protected Integer SsoServerServerStatus = new Integer(1);

    /**
     * Variable for storing the value of "SsoServerServerPort".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.8.1.1.4".
     */
    protected Integer SsoServerServerPort = new Integer(1);

    /**
     * Variable for storing the value of "SsoServerServerHostName".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.8.1.1.3".
     */
    protected String SsoServerServerHostName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerServerProtocol".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.8.1.1.2".
     */
    protected String SsoServerServerProtocol = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerServerId".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.8.1.1.1".
     */
    protected Integer SsoServerServerId = new Integer(1);


    /**
     * Constructor for the "SsoServerServerEntry" group.
     */
    public SsoServerServerEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "SsoServerServerStatus" variable.
     */
    public Integer getSsoServerServerStatus() throws SnmpStatusException {
        return SsoServerServerStatus;
    }

    /**
     * Getter for the "SsoServerServerPort" variable.
     */
    public Integer getSsoServerServerPort() throws SnmpStatusException {
        return SsoServerServerPort;
    }

    /**
     * Getter for the "SsoServerServerHostName" variable.
     */
    public String getSsoServerServerHostName() throws SnmpStatusException {
        return SsoServerServerHostName;
    }

    /**
     * Getter for the "SsoServerServerProtocol" variable.
     */
    public String getSsoServerServerProtocol() throws SnmpStatusException {
        return SsoServerServerProtocol;
    }

    /**
     * Getter for the "SsoServerServerId" variable.
     */
    public Integer getSsoServerServerId() throws SnmpStatusException {
        return SsoServerServerId;
    }

}
