package com.sun.identity.monitoring;

//
// Generated by mibgen version 5.1 (05/20/05) when compiling SUN-OPENSSO-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SsoServerSAML1CacheEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.42.2.230.3.1.1.2.1.16.1.1.
 */
public class SsoServerSAML1CacheEntry implements SsoServerSAML1CacheEntryMBean, Serializable {

    /**
     * Variable for storing the value of "SsoServerSAML1CacheMisses".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.16.1.1.6".
     */
    protected Long SsoServerSAML1CacheMisses = new Long(1);

    /**
     * Variable for storing the value of "SsoServerSAML1CacheHits".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.16.1.1.5".
     */
    protected Long SsoServerSAML1CacheHits = new Long(1);

    /**
     * Variable for storing the value of "SsoServerSAML1CacheWrites".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.16.1.1.4".
     */
    protected Long SsoServerSAML1CacheWrites = new Long(1);

    /**
     * Variable for storing the value of "SsoServerSAML1CacheReads".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.16.1.1.3".
     */
    protected Long SsoServerSAML1CacheReads = new Long(1);

    /**
     * Variable for storing the value of "SsoServerSAML1CacheName".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.16.1.1.2".
     */
    protected String SsoServerSAML1CacheName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SsoServerSAML1CacheIndex".
     * The variable is identified by: "1.3.6.1.4.1.42.2.230.3.1.1.2.1.16.1.1.1".
     */
    protected Integer SsoServerSAML1CacheIndex = new Integer(1);


    /**
     * Constructor for the "SsoServerSAML1CacheEntry" group.
     */
    public SsoServerSAML1CacheEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "SsoServerSAML1CacheMisses" variable.
     */
    public Long getSsoServerSAML1CacheMisses() throws SnmpStatusException {
        return SsoServerSAML1CacheMisses;
    }

    /**
     * Getter for the "SsoServerSAML1CacheHits" variable.
     */
    public Long getSsoServerSAML1CacheHits() throws SnmpStatusException {
        return SsoServerSAML1CacheHits;
    }

    /**
     * Getter for the "SsoServerSAML1CacheWrites" variable.
     */
    public Long getSsoServerSAML1CacheWrites() throws SnmpStatusException {
        return SsoServerSAML1CacheWrites;
    }

    /**
     * Getter for the "SsoServerSAML1CacheReads" variable.
     */
    public Long getSsoServerSAML1CacheReads() throws SnmpStatusException {
        return SsoServerSAML1CacheReads;
    }

    /**
     * Getter for the "SsoServerSAML1CacheName" variable.
     */
    public String getSsoServerSAML1CacheName() throws SnmpStatusException {
        return SsoServerSAML1CacheName;
    }

    /**
     * Getter for the "SsoServerSAML1CacheIndex" variable.
     */
    public Integer getSsoServerSAML1CacheIndex() throws SnmpStatusException {
        return SsoServerSAML1CacheIndex;
    }

}
