#!/bin/sh
#
# The contents of this file are subject to the terms
# of the Common Development and Distribution License
# (the License). You may not use this file except in
# compliance with the License.
#
# You can obtain a copy of the License at
# https://opensso.dev.java.net/public/CDDLv1.0.html or
# opensso/legal/CDDLv1.0.txt
# See the License for the specific language governing
# permission and limitations under the License.
#
# When distributing Covered Code, include this CDDL
# Header Notice in each file and include the License file
# at opensso/legal/CDDLv1.0.txt.
# If applicable, add the following below the CDDL Header,
# with the fields enclosed by brackets [] replaced by
# your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"
#
# $Id: amtune-prepareDSTuner,v 1.1 2007-02-23 23:41:26 bt199000 Exp $
#
# Copyright 2007 Sun Microsystems Inc. All Rights Reserved
#
########################################################################
getListDefaultAMIndexes() {

    index_ldif_file=$IS_CONFIG_DIR/ldif/index.ldif
    if [ ! -f "$index_ldif_file" ]; then
        index_ldif_file=$IS_CONFIG_DIR/index.ldif
        if [ ! -f "$index_ldif_file" ]; then
            $ECHO
            exit 1
	fi
    fi

    $ECHO `$GREP "dn: " $index_ldif_file | $AWK -F" " '{ print $2 }' | $AWK -F"," '{ print $1 }' | $AWK -F"=" '{ print $2 }'`
}

prepareDirectoryTuner() {
    $ECHO `gettext "Preparing Directory Server Tuner..."`
    $ECHO $LINE_SEP
    $ECHO `gettext "Determining Current Settings..."`

    ROOT_SUFFIX=`getConfigEntry "com.iplanet.am.rootsuffix"`
    DS_INSTANCE_DIR=`getInstanceDir`

    ###############ACI############################
    #NormalizeDNandReplaceComma "$ROOT_SUFFIX" "_"
    #
    #if [ "$OSTYPE" = "Linux" ]; then
    #    replaceCharacter "$NMDN" "&" "\\\&"
    #else
    #    replaceCharacter "$NMDN" "&" "\&"
    #fi
    #NM_SUFFIX=$NEWSTR
    ##############################################

    tmp_file=/tmp/amtune-directory
    ds_tar_file=$DS_TAR_DIR/amtune-directory.tar

    if [ -f $ds_tar_file ]; then
        $RM $ds_tar_file
    fi

    $ECHO `gettext "Creating Directory Server Tuner tar file: $ds_tar_file"`

    ds_version=`getDSVersion`
    list_default_am_indexes=`getListDefaultAMIndexes`
    if [ "$list_default_am_indexes" = "" ]; then
	$ECHO "WARNING: Cann't find Access Manager Index file  $IS_CONFIG_DIR/ldif/index.ldif.  Use default list."
	list_default_am_indexes="nsRoleDN memberof iplanet-am-static-group-dn iplanet-am-modifiable-by iplanet-am-user-federation-info-key sunxmlkeyvalue o ou sunPreferredDomain associatedDomain sunOrganizationAlias"
    fi

    $CP $AMTUNE_UTILS_SCRIPT /tmp/amtune-utils
    $CP $SCRIPT_LOCATION/amtune-directory.template $tmp_file

    replace_line $tmp_file "DS_HOST="                   "DS_HOST='$DS_HOST'"
    replace_line $tmp_file "DS_PORT="                   "DS_PORT='$DS_PORT'"
    replace_line $tmp_file "ROOT_SUFFIX="               "ROOT_SUFFIX='$ROOT_SUFFIX'"
    replace_line $tmp_file "DIRMGR_UID="                "DIRMGR_UID='$DIRMGR_UID'"
    replace_line $tmp_file "RAM_DISK="                  "RAM_DISK='$RAM_DISK'"
    replace_line $tmp_file "DS_INSTANCE_DIR="           "DS_INSTANCE_DIR='$DS_INSTANCE_DIR'"
    replace_line $tmp_file "OSTYPE="           		"OSTYPE='$OSTYPE'"
    replace_line $tmp_file "DS_VERSION="          	"DS_VERSION='$ds_version'"
    replace_line $tmp_file "list_am_default_index="     "    list_am_default_index='$list_default_am_indexes'"

    ################################ACI###################################################
    #replace_line $tmp_file "ENABLE_MODE="               "ENABLE_MODE='$ENABLE_MODE'"
    #replace_line $tmp_file "NM_SUFFIX="                 "NM_SUFFIX='$NM_SUFFIX'"
    #replace_line $tmp_file "ORG_OBJECT_CLASS="          "ORG_OBJECT_CLASS='$ORG_OBJECT_CLASS'"
    ######################################################################################

    chmod +x $tmp_file
    #################################ACI#################################################################
    #$TAR cvf $ds_tar_file -C /tmp amtune-directory -C /tmp amtune-utils -C $SCRIPT_LOCATION remacis.ldif
    #####################################################################################################

    $TAR cvf $ds_tar_file -C /tmp amtune-directory -C /tmp amtune-utils

    $RM $tmp_file

    $ECHO 
    $ECHO `gettext "Directory Server Tuner tar file: $ds_tar_file"`
    $ECHO `gettext "Steps to tune directory server:"`
    $ECHO `gettext "1.  Copy the DS Tuner tar to the DS System"`
    $ECHO `gettext "2.  Untar the DS Tuner in a temporary location"`
    $ECHO `gettext "3.  Execute the following script in 'REVIEW' mode : amtune-directory"`
    $ECHO `gettext "4.  Review carefully the recommended tunings for DS"`
    $ECHO `gettext "5.  If you are sure of applying these changes to DS, modify the following lines in amtune-directory"`
    $ECHO `gettext "	a.  AMTUNE_MODE="`
    $ECHO `gettext "	These parameters can also be modified or left unchange to use default values"`
    $ECHO `gettext "	b.  AMTUNE_LOG_LEVEL="`
    $ECHO `gettext "	c.  AMTUNE_DEBUG_FILE_PREFIX="`
    $ECHO `gettext "	d.  DB_BACKUP_DIR_PREFIX="`
    if [ `$ECHO $ds_version | $CUT -c1` -le 5 ]; then
        $ECHO `gettext "Its highly recommended to run db2bak before running amtune-directory"`
    else
        $ECHO `gettext "Its highly recommended to run dsadm backup before running amtune-directory"`
    fi
    $ECHO 
}
#############################################################################
# Start of main program
#############################################################################
# This flag is used only when Access Manager is deployed as single
# web-application.
##@SINGLEWAR_FLAG@

SCRIPT_LOCATION=`dirname $0`
AMTUNE_SCRIPT_RECORD_STRING="AMTUNE_DS_SCRIPT"

# import the environment
if [ -f $SCRIPT_LOCATION/amtune-env ]; then
    if [ ! "$INIT_STATUS" = "INIT_COMPLETE" ]; then
        . $SCRIPT_LOCATION/amtune-env
    fi
fi

ECHO_MSG "Access Manager - Directory Server Tuner Preparation Script"

DS_TAR_DIR=$SCRIPT_LOCATION

prepareDirectoryTuner	| eval $OUTPUT_TYPE

ECHO_MSG $PARA_SEP 
