#!/bin/sh
# The contents of this file are subject to the terms
# of the Common Development and Distribution License
# (the License). You may not use this file except in
# compliance with the License.
#
# You can obtain a copy of the License at
# https://opensso.dev.java.net/public/CDDLv1.0.html or
# opensso/legal/CDDLv1.0.txt
# See the License for the specific language governing
# permission and limitations under the License.
#
# When distributing Covered Code, include this CDDL
# Header Notice in each file and include the License file
# at opensso/legal/CDDLv1.0.txt.
# If applicable, add the following below the CDDL Header,
# with the fields enclosed by brackets [] replaced by
# your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"
#
# $Id: amtune,v 1.1 2007-02-23 23:41:23 bt199000 Exp $
#
# Copyright 2007 Sun Microsystems Inc. All Rights Reserved
#
###############################################################################
#############################################################################
# Start of main program
#############################################################################
SCRIPT_LOCATION=`/usr/bin/dirname $0`
AMTUNE_SCRIPT_RECORD_STRING="AMTUNE_MAIN_SCRIPT"

# import the environment
if [ -f $SCRIPT_LOCATION/amtune-env ]; then
	if [ ! "$INIT_STATUS" = "INIT_COMPLETE" ]; then
    	. $SCRIPT_LOCATION/amtune-env
    fi
fi

ECHO_MSG "Access Manager Tuning Script"
ECHO_MSG $LINE_SEP

#Tune OS
if [ "$AMTUNE_TUNE_OS" = "true" ]; then
    if [ -f $AMTUNE_BIN_DIR/amtune-os ]; then
        . $AMTUNE_BIN_DIR/amtune-os
    else
        ECHO_MSG "WARNING: amtune-os is not running. Script is not found in $AMTUNE_BIN_DIR"
    fi
fi

#Tune Web Server/Application Server
if [ "$AMTUNE_TUNE_WEB_CONTAINER" = "true" ]; then
    webContainerToTune  | eval $OUTPUT_TYPE
    if [ "$WC_CONFIG" != "" ]; then
        if [ -f $AMTUNE_BIN_DIR/${WC_CONFIG} ]; then
            . $AMTUNE_BIN_DIR/${WC_CONFIG}
        else
            ECHO_MSG "WARNING: ${WC_CONFIG} is not running. Script is not found in $AMTUNE_BIN_DIR"
        fi
    fi
fi

#Tune Directory Server
if [ "$AMTUNE_TUNE_DS" = "true" ]; then
    if [ -f $AMTUNE_BIN_DIR/amtune-prepareDSTuner ]; then
        . $AMTUNE_BIN_DIR/amtune-prepareDSTuner
    else
        ECHO_MSG "WARNING: amtune-prepareDSTuner is not running. Script is not found in $AMTUNE_BIN_DIR"
    fi
fi

#Tune Access Manager
if [ "$AMTUNE_TUNE_IDENTITY" = "true" ]; then
    if [ -f $AMTUNE_BIN_DIR/amtune-identity ]; then
        . $AMTUNE_BIN_DIR/amtune-identity
    else
        ECHO_MSG "WARNING: amtune-identity is not running. Script is not found in $AMTUNE_BIN_DIR"
    fi
fi

ECHO_MSG "Tuning Complete"
ECHO_MSG $CHAPTER_SEP
